# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: XiboSignageLtd.XiboPlayer
PackageVersion: 3.305.1
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: msi
  InstallerUrl: https://xibosignage.com/api/downloads/382
  InstallerSha256: 0B69C125521AED037C8B8375E00B93A12BE1BB0D2792BC43C6CED9754B3B7F7F
  ProductCode: '{5D2C1BAB-568D-4B70-A17F-534E89155499}'
ManifestType: installer
ManifestVersion: 1.2.0

